server:
  port: 8082

spring:
  application:
    name: permit-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/workpermit}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cache:
    type: redis

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-jwt-key-my-super-secret-jwt-key}
